### ISSUE TITLE
Cant login at discord server

### ISSUE THREAD

**Issue by Metacowboy** [passivebot/midjourney-automation-bot#2]
upscale_midjourney_downloader.py
Error on line 117 , it gets a timeout when try to login

With OSX 13.4  Python3.9 running in  Conda env 
`event = await wait_helper.result()
playwright._impl._api_types.TimeoutError: Timeout 15000ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://discord.com/channels/@me" until 'load'
============================================================`

#Solved 
the creditentials.txt
need the format 
email@host.com
#password

Would be nice if we could use a discord bot Auth key instead of -user creditentials 
than it would run conform with the discord rules

**Comment by harmindersinghnijjar** [comment]
Are you still needing help? If not, I'll go ahead and close out this issue.
